### ISSUE TITLE
Adding menu, and congratulating on completion. Plus including the menu bar on top.

### ISSUE THREAD

**Issue by mayankpm** [acmpesuecc/Slide#19]

**Comment by bluishhh** [comment]
hey @mayankpm, all the best on this one. Be ready for a crazy point boost if you succeed in this :)

**Comment by bluishhh** [comment]
!bounty 15

**Comment by bluishhh** [comment]
Enthu points assigned

**Comment by bluishhh** [comment]
@mayankpm please show me your progress in an hour
