### ISSUE TITLE
Missing buttons 😰

### ISSUE THREAD

**Issue by bluishhh** [acmpesuecc/Slide#4]
If you look closely, you'll see that the main function has some buttons being created. But where did they go? Bring em back!!!

**Comment by bluishhh** [comment]
hey @Vr-00, best of luck on this one

**Comment by AiMeN0425** [comment]
can i work on this?

**Comment by bluishhh** [comment]
@AiMeN0425

**Comment by sean-18** [comment]
@bluishhh can i do this 
pes2ug21cs924
sean sougaijam

**Comment by TharunK41** [comment]
can I work on this

**Comment by SarthakSKumar** [comment]
I would like to work on this issue. Pleae assign!

**Comment by bluishhh** [comment]
@AiMeN0425 may i know where you are seated?

**Comment by SarthakSKumar** [comment]
Is someone working on this issue?

**Comment by SarthakSKumar** [comment]
@bluishhh Can I get assigned to this issue? I suppose the blocking time is over for the previous assignee

**Comment by daspragya** [comment]
Can I do this?

**Comment by bluishhh** [comment]
!bounty 40
