### ISSUE TITLE
Glitch in the game

### ISSUE THREAD

**Issue by bluishhh** [acmpesuecc/Slide#5]
![image](https://user-images.githubusercontent.com/92492766/196777008-7473125f-0488-4583-8c21-56e7df11d0e7.png)
Go on a hunt and look for the lil glitch that's going on for some ez points.</br>
Found it? Mail your answer to [bluishhh](https://github.com/bluishhh) and mention a maintainer in the comment to check your mail.</br>
(Hint: finding this will help you with [this](https://github.com/acmpesuecc/Slide/issues/4) as well ;)

**Comment by AiMeN0425** [comment]
can i do this?

**Comment by samarth777** [comment]
can you assign this to me

**Comment by bluishhh** [comment]
Hey @AiMeN0425, atb on finding it, my mail is available on my profile, so lmk if you find it :)

**Comment by tanishkapasarad** [comment]
can i work on this? tanishka pasarad

**Comment by samarth777** [comment]
can you check your mail

**Comment by samarth777** [comment]
@bluishhh

**Comment by sphoorthiY** [comment]
is it open ?
can i do this 
PES2UG21CS241

**Comment by GSL006** [comment]
is it open
SRN:PES2202200752

**Comment by SarthakSKumar** [comment]
Could you please check your mail @bluishhh :)

**Comment by DhatriC123** [comment]
can i work on this

**Comment by Vaarun-Kamath** [comment]
Caan i work on this pls :)
