### ISSUE TITLE
Dynamic grid size challenge (For chads)

### ISSUE THREAD

**Issue by bluishhh** [acmpesuecc/Slide#6]
The grid size is hard coded in the game. Doesnt give the user an option to change, does it? How about find a way to give users the liberty to choose between 4x4, 5x5, 6x6 and 7x7 grids?</br>
Solve this for some them ✨Bonus✨ points.

**Comment by cubed-guy** [comment]
Can I be assigned this?

**Comment by AiMeN0425** [comment]
can i do this?

**Comment by Vr-001** [comment]
pls assign me this

**Comment by cubed-guy** [comment]
Can I be assigned to this?
PES2UG21CS477 Sanket Padhi

**Comment by cubed-guy** [comment]
Can I be assigned to this?
PES2UG21CS477 Sanket Padhi
@NavinShrinivas

**Comment by NavinShrinivas** [comment]
Sure!

**Comment by NavinShrinivas** [comment]
Sure @cubed-guy gets assigned to this repo!

**Comment by Vaarun-Kamath** [comment]
hey can i work on this :)
