### ISSUE TITLE
README.md update requiered

### ISSUE THREAD

**Issue by bluishhh** [acmpesuecc/Slide#7]
Add a few lines in the description of slide. Best writings win the points :)

**Comment by pranavvatsa** [comment]
can i be assigned this, pranav vatsa

**Comment by AiMeN0425** [comment]
can i do this?

**Comment by tanishkapasarad** [comment]
can i work on this? tanishka pasarad

**Comment by pkmrs** [comment]
Can I be assigned to this, prem kumar s

**Comment by druva344** [comment]
can i please be assigned to this

**Comment by siddarthpai** [comment]
hey can I work on this 
PES2UG21CS925
SIDDARTH.D.PAI

**Comment by SahilPrabhu** [comment]
Hey can i be assigned to this? Sahil (PES2202200830)

**Comment by arihan01** [comment]
Can I be assigned to this? 
Arihan
PES2UG20CS065

**Comment by AtharvaAnilChanda** [comment]
Hey Isha !! Can I be assigned this ?? 
Atharva Anil Chanda 
PES2UG20CS075

**Comment by architanand95** [comment]
Can I be assigned this ??

**Comment by TharunK41** [comment]
can I be assigned to this @bluishhh #7
