### ISSUE TITLE
Let's take a picture, shall we? Part-1: Slice em

### ISSUE THREAD

**Issue by bluishhh** [acmpesuecc/Slide#8]
Now, rearranging numbers sounds too basic, doesn't it? Let's do some thing fun, add images instead of numbers :D </br>

1. Slice the picture of my beloved dog brandy, [brandy.png](https://github.com/acmpesuecc/Slide/blob/main/brandy.png) into 4x4, 5x5, 6x6 and 7x7 grids.
2. Save the individual picture names as brandy_Grid-number_Piece-number.png.</br>
Example - brandy_4x4_2  will be -</br>

<img width="228" alt="delete" src="https://user-images.githubusercontent.com/92492766/196789748-1555488a-bf30-4f8c-ae84-6f31df2d091d.png">

Note: Make sure to follow [Contributor guidelines](https://github.com/acmpesuecc/Slide/blob/main/contribute.md) , failing which might lead to deduction in points

**Comment by bluishhh** [comment]
hello @rishikakinger ,  you may start working working on this issue now

**Comment by Ganther3301** [comment]
hey can i be assigned to this issue

**Comment by daspragya** [comment]
can i work on this?

**Comment by Vaarun-Kamath** [comment]
hey can i work on this pls :)

**Comment by ramselvaraj** [comment]
hey can i work on this?

**Comment by bluishhh** [comment]
hey @Ganther3301 , you may work on this now

**Comment by abhiraj2** [comment]
Can I work on this?

**Comment by ad1tya24** [comment]
I would like to work on this

**Comment by MotoMoto418** [comment]
Hi! I'd like to work on this issue
