### ISSUE TITLE
Let's take a picture, shall we? Part-2: Spice em 

### ISSUE THREAD

**Issue by bluishhh** [acmpesuecc/Slide#9]
Now, rearranging numbers sounds too basic, doesn't it? Let's do some thing fun, add images instead of numbers :D</br>

Make the respective images render on the face of each block. (brandy_4x4_1 should appear as face for block 1 on a 4x4 grid.

Resources: [Display image in pygame](https://www.geeksforgeeks.org/python-display-images-with-pygame/)

**Note:** 
Make sure to follow [Contributor guidelines](https://github.com/acmpesuecc/Slide/blob/main/contribute.md) , failing which might lead to deduction in points

**Comment by bluishhh** [comment]
Hii @rishikakinger , you may start working on this now

**Comment by mayankpm** [comment]
Hi, Can I be assigned to this? Thank You (PES2UG21CS932)

**Comment by ramselvaraj** [comment]
hey can i be assigned to this?

**Comment by abhiraj2** [comment]
Can I be assigned to this?
